import sys

with open('src/mnemo_mcp/db.py', 'r') as f:
    lines = f.readlines()

new_content = []
skip = False
for line in lines:
    if 'def import_jsonl(self, data: str | list | dict, mode: str = "merge") -> dict:' in line:
        new_content.append('    def import_jsonl(self, data: str | list | dict, mode: str = "merge") -> dict:\n')
        new_content.append('        """Import memories from JSONL string.\n')
        new_content.append('\n')
        new_content.append('        Args:\n')
        new_content.append('            data: JSONL string (one JSON object per line).\n')
        new_content.append('            mode: "merge" (skip existing) or "replace" (clear + import).\n')
        new_content.append('\n')
        new_content.append('        Returns:\n')
        new_content.append('            Dict with import stats (imported, skipped, rejected).\n')
        new_content.append('        """\n')
        new_content.append('        if mode == "replace":\n')
        new_content.append('            self._conn.execute("DELETE FROM memories")\n')
        new_content.append('            if self._vec_enabled:\n')
        new_content.append('                self._conn.execute("DELETE FROM memories_vec")\n')
        new_content.append('\n')
        new_content.append('        imported = 0\n')
        new_content.append('        skipped = 0\n')
        new_content.append('        rejected = 0\n')
        new_content.append('\n')
        new_content.append('        if isinstance(data, list):\n')
        new_content.append('            lines_data = data\n')
        new_content.append('        elif isinstance(data, dict):\n')
        new_content.append('            lines_data = [data]\n')
        new_content.append('        elif isinstance(data, str):\n')
        new_content.append('            lines_data = []\n')
        new_content.append('            for line_str in data.strip().split("\\n"):\n')
        new_content.append('                line_str = line_str.strip()\n')
        new_content.append('                if line_str:\n')
        new_content.append('                    try:\n')
        new_content.append('                        lines_data.append(json.loads(line_str))\n')
        new_content.append('                    except Exception:\n')
        new_content.append('                        rejected += 1\n')
        new_content.append('        else:\n')
        new_content.append('            lines_data = []\n')
        new_content.append('\n')
        new_content.append('        BATCH_SIZE = 900\n')
        new_content.append('        now = _now_iso()\n')
        new_content.append('\n')
        new_content.append('        for i in range(0, len(lines_data), BATCH_SIZE):\n')
        new_content.append('            batch_items = lines_data[i : i + BATCH_SIZE]\n')
        new_content.append('            batch_imported, batch_skipped, batch_rejected = self._process_import_batch(\n')
        new_content.append('                batch_items, mode, now\n')
        new_content.append('            )\n')
        new_content.append('            imported += batch_imported\n')
        new_content.append('            skipped += batch_skipped\n')
        new_content.append('            rejected += batch_rejected\n')
        new_content.append('\n')
        new_content.append('        self._conn.commit()\n')
        new_content.append('        if imported > 0:\n')
        new_content.append('            logger.info(f"[AUDIT] import count={imported} mode={mode}")\n')
        new_content.append('        return {"imported": imported, "skipped": skipped, "rejected": rejected}\n')
        new_content.append('\n')
        new_content.append('    def _process_import_batch(\n')
        new_content.append('        self, batch_items: list[dict], mode: str, now: str\n')
        new_content.append('    ) -> tuple[int, int, int]:\n')
        new_content.append('        """Validate, format, and execute database insertion for a single batch."""\n')
        new_content.append('        imported = 0\n')
        new_content.append('        skipped = 0\n')
        new_content.append('        rejected = 0\n')
        new_content.append('        parsed_batch = []\n')
        new_content.append('\n')
        new_content.append('        # Validate batch\n')
        new_content.append('        for mem in batch_items:\n')
        new_content.append('            try:\n')
        new_content.append('                memory_id = mem.get("id", uuid.uuid4().hex)\n')
        new_content.append('                content = mem.get("content", "")\n')
        new_content.append('\n')
        new_content.append('                if len(content) > MAX_CONTENT_LENGTH:\n')
        new_content.append('                    logger.warning(\n')
        new_content.append('                        f"[AUDIT] import rejected id={memory_id} "\n')
        new_content.append('                        f"len={len(content)} exceeds {MAX_CONTENT_LENGTH}"\n')
        new_content.append('                    )\n')
        new_content.append('                    rejected += 1\n')
        new_content.append('                    continue\n')
        new_content.append('\n')
        new_content.append('                parsed_batch.append((memory_id, mem, content))\n')
        new_content.append('            except Exception:\n')
        new_content.append('                rejected += 1\n')
        new_content.append('                continue\n')
        new_content.append('\n')
        new_content.append('        if not parsed_batch:\n')
        new_content.append('            return imported, skipped, rejected\n')
        new_content.append('\n')
        new_content.append('        to_insert = []\n')
        new_content.append('        for memory_id, mem, content in parsed_batch:\n')
        new_content.append('            tags = mem.get("tags", [])\n')
        new_content.append('            tags_json = json.dumps(tags) if isinstance(tags, list) else tags\n')
        new_content.append('\n')
        new_content.append('            to_insert.append(\n')
        new_content.append('                (\n')
        new_content.append('                    memory_id,\n')
        new_content.append('                    content,\n')
        new_content.append('                    mem.get("category", "general"),\n')
        new_content.append('                    tags_json,\n')
        new_content.append('                    mem.get("source"),\n')
        new_content.append('                    mem.get("created_at", now),\n')
        new_content.append('                    mem.get("updated_at", now),\n')
        new_content.append('                    mem.get("access_count", 0),\n')
        new_content.append('                    mem.get("last_accessed", now),\n')
        new_content.append('                )\n')
        new_content.append('            )\n')
        new_content.append('\n')
        new_content.append('        if to_insert:\n')
        new_content.append('            cursor = self._conn.cursor()\n')
        new_content.append('            if mode == "replace":\n')
        new_content.append('                cursor.executemany(\n')
        new_content.append('                    """INSERT OR REPLACE INTO memories\n')
        new_content.append('                       (id, content, category, tags, source,\n')
        new_content.append('                        created_at, updated_at, access_count, last_accessed)\n')
        new_content.append('                       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",\n')
        new_content.append('                    to_insert,\n')
        new_content.append('                )\n')
        new_content.append('                imported += len(to_insert)\n')
        new_content.append('            else:\n')
        new_content.append('                cursor.executemany(\n')
        new_content.append('                    """INSERT OR IGNORE INTO memories\n')
        new_content.append('                       (id, content, category, tags, source,\n')
        new_content.append('                        created_at, updated_at, access_count, last_accessed)\n')
        new_content.append('                       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",\n')
        new_content.append('                    to_insert,\n')
        new_content.append('                )\n')
        new_content.append('                inserted_batch = cursor.rowcount\n')
        new_content.append('                imported += inserted_batch\n')
        new_content.append('                skipped += len(to_insert) - inserted_batch\n')
        new_content.append('\n')
        new_content.append('        return imported, skipped, rejected\n')
        skip = True
    elif 'def archive_old_memories(' in line:
        skip = False
        new_content.append(line)
    elif not skip:
        new_content.append(line)

with open('src/mnemo_mcp/db.py', 'w') as f:
    f.writelines(new_content)
