"""Hybrid-search parity: D1-FTS + Vectorize KNN + app-side RRF (k=60).

The FTS-only golden (tests/fixtures/cf_golden_topk.json) was generated by the
local SQLite MemoryDB.search over the same corpus; the D1 path must reproduce its
top-3 ordering because FakeD1Http runs the identical FTS5 (porter unicode61, same
bm25 weights) and the ranking math is ported verbatim. The RRF test proves the
Vectorize fusion path lifts a doc that both FTS and the vector agree on.
"""

from mcp_core.storage import D1Backend, VectorizeBackend

from mnemo_mcp.db_cf import MemoryDBD1


def _fts_db(fake_d1_http, fake_vectorize_http, sub="u1"):
    return MemoryDBD1(
        d1=D1Backend(base_url="http://d1.internal", http=fake_d1_http),
        vectorize=VectorizeBackend(
            base_url="http://vectorize.internal", idx="i", http=fake_vectorize_http
        ),
        sub=sub,
        embedding_dims=0,  # FTS-only, matches golden generator
    )


def test_fts_only_search_matches_golden(
    fake_d1_http, fake_vectorize_http, cf_corpus, cf_golden_topk
):
    db = _fts_db(fake_d1_http, fake_vectorize_http)
    for d in cf_corpus:
        db.add(d["content"], category=d["category"], tags=d["tags"], source=d["source"])
    for query, golden in cf_golden_topk.items():
        got = [r["content"][:40] for r in db.search(query, limit=10)]
        # top-3 ordering parity is the contract (bm25 + recency on same corpus).
        assert got[:3] == golden[:3], f"query={query!r}: {got[:3]} != {golden[:3]}"


def test_rrf_fusion_combines_fts_and_vec(fake_d1_http, fake_vectorize_http):
    db = MemoryDBD1(
        d1=D1Backend(base_url="http://d1.internal", http=fake_d1_http),
        vectorize=VectorizeBackend(
            base_url="http://vectorize.internal", idx="i", http=fake_vectorize_http
        ),
        sub="u1",
        embedding_dims=4,
    )
    db.add("alpha beta gamma", embedding=[1.0, 0.0, 0.0, 0.0])
    db.add("delta epsilon", embedding=[0.0, 1.0, 0.0, 0.0])
    db._vec.wait_until_indexed(poll_interval=0, max_wait=1)  # E.3
    out = db.search("alpha", embedding=[1.0, 0.0, 0.0, 0.0], limit=2)
    assert out[0]["content"] == "alpha beta gamma"  # FTS + vec agree -> top


def test_vec_only_hit_hydrated_from_d1(fake_d1_http, fake_vectorize_http):
    """A doc found only by the vector (not FTS) is hydrated from D1 and ranked."""
    db = MemoryDBD1(
        d1=D1Backend(base_url="http://d1.internal", http=fake_d1_http),
        vectorize=VectorizeBackend(
            base_url="http://vectorize.internal", idx="i", http=fake_vectorize_http
        ),
        sub="u1",
        embedding_dims=4,
    )
    db.add("totally unrelated lexical text", embedding=[1.0, 0.0, 0.0, 0.0])
    db._vec.wait_until_indexed(poll_interval=0, max_wait=1)
    out = db.search("zzzznomatch", embedding=[1.0, 0.0, 0.0, 0.0], limit=5)
    assert len(out) == 1 and out[0]["content"] == "totally unrelated lexical text"
